

services:
  db:
    image: postgres:13
    env_file:
      - .env.production
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    env_file:
      - .env.production
    command: bash -c "flask db upgrade && gunicorn --bind 0.0.0.0:5000 run:app"
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: run.py

    depends_on:
      - db
  nginx:
      container_name: nginx
      restart: unless-stopped
      image: nginx
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
      depends_on:
        - web
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email spenceralanhowe@gmail.com -d thehoweranchpayment.com --agree-tos
volumes:
  postgres_data:

