

services:
  db:
    image: postgres:13
    env_file:
      - .env.production
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    env_file:
      - .env.production
    command: bash -c "flask db upgrade && gunicorn --bind 0.0.0.0:5000 run:app"
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: run.py

    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "80:80"        # HTTP port
      - "443:443"      # HTTPS port
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf  # Nginx config
    - ./ssl:/etc/nginx/ssl                            # Mount your SSL directory
    - /etc/letsencrypt:/etc/letsencrypt                # For future Let's Encrypt certs
    - /var/lib/letsencrypt:/var/lib/letsencrypt
    - /usr/share/nginx/html:/usr/share/nginx/html
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./letsencrypt:/var/lib/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    entrypoint: "/bin/sh -c 'trap exit TERM; certbot certonly --webroot -w /usr/share/nginx/html -d www.thehoweranchpayment.com --non-interactive --agree-tos --email spenceralanhowe@gmail.com && while :; do sleep 12h & wait $${!}; certbot renew --post-hook \"nginx -s reload\"; done;'"



volumes:
  postgres_data:

