-- Insert Springtime Magic with the Mini Moos events
-- Four dates: Feb 22, Mar 1, Mar 15, Mar 22 (2026)
-- Time slots: 2:00 PM to 5:00 PM start times in 15-minute increments
-- Each event is 2 hours long
-- Price: $350, Private: false, is_private: true (corrected), Max capacity: 5

INSERT INTO event (title, start, "end", description, price_per_ticket, private, is_private, is_booked, max_capacity, user_id)
VALUES 

-- February 22, 2026 (Sunday) - Time slots from 2:00 PM to 5:00 PM
('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-02-22 14:00:00', timestamp '2026-02-22 16:00:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-02-22 14:15:00', timestamp '2026-02-22 16:15:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-02-22 14:30:00', timestamp '2026-02-22 16:30:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-02-22 14:45:00', timestamp '2026-02-22 16:45:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-02-22 15:00:00', timestamp '2026-02-22 17:00:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-02-22 15:15:00', timestamp '2026-02-22 17:15:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-02-22 15:30:00', timestamp '2026-02-22 17:30:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-02-22 15:45:00', timestamp '2026-02-22 17:45:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-02-22 16:00:00', timestamp '2026-02-22 18:00:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-02-22 16:15:00', timestamp '2026-02-22 18:15:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-02-22 16:30:00', timestamp '2026-02-22 18:30:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-02-22 16:45:00', timestamp '2026-02-22 18:45:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully stuffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-02-22 17:00:00', timestamp '2026-02-22 19:00:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

-- March 1, 2026 (Sunday) - Time slots from 2:00 PM to 5:00 PM
('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-01 14:00:00', timestamp '2026-03-01 16:00:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-01 14:15:00', timestamp '2026-03-01 16:15:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-01 14:30:00', timestamp '2026-03-01 16:30:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-01 14:45:00', timestamp '2026-03-01 16:45:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-01 15:00:00', timestamp '2026-03-01 17:00:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-01 15:15:00', timestamp '2026-03-01 17:15:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-01 15:30:00', timestamp '2026-03-01 17:30:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-01 15:45:00', timestamp '2026-03-01 17:45:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-01 16:00:00', timestamp '2026-03-01 18:00:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-01 16:15:00', timestamp '2026-03-01 18:15:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-01 16:30:00', timestamp '2026-03-01 18:30:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-01 16:45:00', timestamp '2026-03-01 18:45:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-01 17:00:00', timestamp '2026-03-01 19:00:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

-- March 15, 2026 (Sunday) - Time slots from 2:00 PM to 5:00 PM
('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-15 14:00:00', timestamp '2026-03-15 16:00:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-15 14:15:00', timestamp '2026-03-15 16:15:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-15 14:30:00', timestamp '2026-03-15 16:30:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-15 14:45:00', timestamp '2026-03-15 16:45:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-15 15:00:00', timestamp '2026-03-15 17:00:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-15 15:15:00', timestamp '2026-03-15 17:15:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-15 15:30:00', timestamp '2026-03-15 17:30:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-15 15:45:00', timestamp '2026-03-15 17:45:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-15 16:00:00', timestamp '2026-03-15 18:00:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-15 16:15:00', timestamp '2026-03-15 18:15:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-15 16:30:00', timestamp '2026-03-15 18:30:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-15 16:45:00', timestamp '2026-03-15 18:45:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-15 17:00:00', timestamp '2026-03-15 19:00:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

-- March 22, 2026 (Sunday) - Time slots from 2:00 PM to 5:00 PM
('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-22 14:00:00', timestamp '2026-03-22 16:00:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-22 14:15:00', timestamp '2026-03-22 16:15:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-22 14:30:00', timestamp '2026-03-22 16:30:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-22 14:45:00', timestamp '2026-03-22 16:45:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-22 15:00:00', timestamp '2026-03-22 17:00:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-22 15:15:00', timestamp '2026-03-22 17:15:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-22 15:30:00', timestamp '2026-03-22 17:30:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-22 15:45:00', timestamp '2026-03-22 17:45:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-22 16:00:00', timestamp '2026-03-22 18:00:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-22 16:15:00', timestamp '2026-03-22 18:15:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-22 16:30:00', timestamp '2026-03-22 18:30:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-22 16:45:00', timestamp '2026-03-22 18:45:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1),

('Springtime Magic with the Mini Moos - Including Professional Photos', timestamp '2026-03-22 17:00:00', timestamp '2026-03-22 19:00:00', 
 '🌸 SPRINGTIME MAGIC WITH THE MINI MOOS: Small Group Experience - Shared with 1-5 families • Early-access boutique setting. Your Springtime Magic Experience Includes: 🐮 Baby Moo kisses & cuddles with our fluffy Highland calves 📸 Three professional mini-session photos with our photographer partner 🌸 A spring fairytale farm setting filled with storybook charm 🐰 Wonderland Tea Time with our bunnies in their enchanted garden 🍓 Seasonal spring treats & refreshing drinks 🐐 Relaxation time with alpacas, mini Highland cows, mini goats and donkeys 🎨 Includes a free project at our make-and-take craft station 🌼 A fully staffed, relaxed experience with guided flow — no crowds, no chaos 🗺️ A whimsical scavenger hunt adventure through our enchanted farm settings with prizes for all ages', 
 350.00, false, true, false, 5, 1);

-- After running the INSERT, use this query to get the new ID numbers:
SELECT 
    id,
    DATE(start) as event_date,
    TO_CHAR(start, 'HH12:MI AM') as start_time,
    TO_CHAR("end", 'HH12:MI AM') as end_time
FROM event 
WHERE title = 'Springtime Magic with the Mini Moos - Including Professional Photos'
ORDER BY start;

-- Summary count by date
SELECT 
    DATE(start) as event_date,
    COUNT(*) as time_slots_per_date
FROM event 
WHERE title = 'Springtime Magic with the Mini Moos - Including Professional Photos'
GROUP BY DATE(start)
ORDER BY DATE(start);