"""Add private field to Event model

Revision ID: 22dcc9224684
Revises: e8fae94d5ca7
Create Date: 2024-09-23 23:15:08.768354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22dcc9224684'
down_revision = 'e8fae94d5ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        # Add the 'private' column with a default of False for existing records
        batch_op.add_column(sa.Column('private', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # Optionally, remove the server_default to avoid setting it on future migrations
    op.alter_column('event', 'private', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('private')

    # ### end Alembic commands ###
