"""Add QR check-in columns

Revision ID: 58839a46443d
Revises: 9deeabb0e9c3
Create Date: 2025-10-07 21:39:33.824406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58839a46443d'
down_revision = '9deeabb0e9c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_in', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('checkin_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('checkin_time')
        batch_op.drop_column('checked_in')

    # ### end Alembic commands ###
