"""Added is_booked column

Revision ID: 687ba997f3a4
Revises: 22dcc9224684
Create Date: 2025-03-10 19:52:35.328850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687ba997f3a4'
down_revision = '22dcc9224684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_booked', sa.Boolean(), nullable=True))
        batch_op.alter_column('private',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('private',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('is_booked')
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###
