"""Add max_capacity to Event model

Revision ID: 6d824813a0f6
Revises: c29490df2808
Create Date: 2025-09-28 03:15:07.343553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d824813a0f6'
down_revision = 'c29490df2808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('max_capacity', sa.Integer(), nullable=False, server_default='50'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'max_capacity')
    # ### end Alembic commands ###