"""add photo_followup_sent column to booking model

Revision ID: 78d1539e7375
Revises: 9303054afad0
Create Date: 2026-01-29 07:37:55.621885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d1539e7375'
down_revision = '9303054afad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_followup_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('photo_followup_sent')

    # ### end Alembic commands ###
