"""Make receipt_sent non-nullable

Revision ID: 90a758e5a7c4
Revises: 9172540de8af
Create Date: 2025-12-05 03:36:46.972470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a758e5a7c4'
down_revision = '9172540de8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('receipt_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('receipt_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
