"""Add receipt_sent column nullable

Revision ID: 9172540de8af
Revises: 939a008e70d6
Create Date: 2025-12-05 02:56:27.998378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9172540de8af'
down_revision = '939a008e70d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_sent', sa.Boolean(), nullable=True))
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('max_capacity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('waiver', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('waiver_order_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waiver', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('waiver_order_id_key'), ['order_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('max_capacity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('receipt_sent')

    # ### end Alembic commands ###
