"""add crypto tables

Revision ID: 9deeabb0e9c3
Revises: 6d824813a0f6
Create Date: 2025-09-30 06:05:35.915751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9deeabb0e9c3'
down_revision = '6d824813a0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('crypto_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('crypto_address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('transaction_hash', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('transaction_hash')
        batch_op.drop_column('crypto_address')
        batch_op.drop_column('crypto_currency')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
