"""reminder

Revision ID: c29490df2808
Revises: d96ae7f7dc09
Create Date: 2025-05-13 19:51:55.287562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29490df2808'
down_revision = 'd96ae7f7dc09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_sent', sa.Boolean(), nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('is_private',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_booked',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('is_booked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_private',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('reminder_sent')

    # ### end Alembic commands ###
