"""Set is_private and is_booked to non-nullable

Revision ID: d96ae7f7dc09
Revises: 687ba997f3a4
Create Date: 2025-03-10 21:49:59.712401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd96ae7f7dc09'
down_revision = '687ba997f3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('private',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_private',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_booked',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('is_booked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_private',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('private',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
